smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -299,14 +299,6 @@ jobs:
               npm i
               npm install
               npm run build
-              # echo "TYPEORM_ENTITIES=./dist/modules/domain/**/*.entity{.ts,.js}" > .env
-              # echo "TYPEORM_HOST=${TYPEORM_HOST}" >> .env
-              # echo "TYPEORM_PORT=${TYPEORM_PORT}" >> .env
-              # echo "TYPEORM_USERNAME=${TYPEORM_USERNAME}" >> .env
-              # echo "TYPEORM_PASSWORD=${TYPEORM_PASSWORD}" >> .env
-              # echo "TYPEORM_DATABASE=${TYPEORM_DATABASE}" >> .env
-              # echo "TYPEORM_MIGRATIONS_DIR=./dist/migrations" >> .env
-              # echo "TYPEORM_MIGRATIONS=./dist/migrations/*.ts" >> .env
               cd ..
               tar -C backend -czvf artifact.tar.gz .
               mkdir -p ~/project/.circleci/ansible/roles/deploy/files/
@@ -352,10 +344,15 @@ jobs:
             command: |
               # export URl=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com 
               # echo $URL
-              # if curl ${URL} | grep "Welcome"; then return 0; else return 1; fi
-              export URl="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/#/employees"
-              echo $URL
-              if curl ${URL} | grep "Welcome"; then exit 0; else exit 1; fi
+              URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+              echo ${URL} 
+              if curl -s ${URL} | grep "Welcome"
+              then
+                  # Change this to 0 after the job fails
+                exit 0
+              else
+                exit 1
+              fi
         # - destroy-environment
         # - revert-migrations
   cloudfront-update:
